# Generated by Django 4.0.5 on 2022-07-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0002_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
