# Generated by Django 4.0.5 on 2022-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0005_rename_avatar_avatar_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={},
        ),
    ]
