# Generated by Django 4.0.5 on 2022-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0006_alter_avatar_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='foto',
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
