# Generated by Django 4.0.5 on 2022-07-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0009_useredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEdit',
        ),
    ]
