# Generated by Django 4.0.5 on 2022-07-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoFinalApp', '0013_remove_mensaje_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='usuario_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
