# Generated by Django 4.0.5 on 2022-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0014_alter_mensaje_usuario_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Articulo'),
        ),
    ]
