# Generated by Django 4.0.5 on 2022-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0018_alter_mensaje_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
