# Generated by Django 4.0.5 on 2022-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0023_alter_mensaje_usuario_receptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
    ]
